name: "Publish"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  llvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v9
        with:
          name: geobacter-rs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build -A nixpkgs.geobacterRustcLlvmPackages | cachix push geobacter-rs
      - run: nix-shell --run "echo OK"
  rustc:
    needs: llvm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v9
        with:
          name: geobacter-rs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build -A nixpkgs.geobacterRustPackages.rustc | cachix push geobacter-rs
      - run: nix-shell --run "echo OK"
  cargo:
    needs: rustc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v9
        with:
          name: geobacter-rs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build -A nixpkgs.geobacterRustPackages.cargo | cachix push geobacter-rs
      - run: nix-shell --run "echo OK"
  rustfmt:
    needs: rustc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v9
        with:
          name: geobacter-rs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build -A nixpkgs.geobacterRustPackages.rustfmt | cachix push geobacter-rs
      - run: nix-shell --run "echo OK"
