name: "Publish"
on:
  push:
    branches:
      - master
jobs:
  llvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v9
        with:
          name: geobacter-rs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: mkdir -p ~/.config/nixpkgs/overlays && ln -s `pwd` ~/.config/nixpkgs/overlays/nixos-geobacter
      - run: (nix-build pkgs/default.nix --verbose --verbose --show-trace -A geobacterRustcLlvmPackages || exit 1) | cachix push geobacter-rs
  rustc:
    needs: llvm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v9
        with:
          name: geobacter-rs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: mkdir -p ~/.config/nixpkgs/overlays && ln -s `pwd` ~/.config/nixpkgs/overlays/nixos-geobacter
      - run: (nix-build pkgs/default.nix --verbose --verbose --show-trace -A geobacterRustPackages.rustc || exit 1) | cachix push geobacter-rs
  cargo:
    needs: rustc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v9
        with:
          name: geobacter-rs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: mkdir -p ~/.config/nixpkgs/overlays && ln -s `pwd` ~/.config/nixpkgs/overlays/nixos-geobacter
      - run: (nix-build pkgs/default.nix --verbose --verbose --show-trace -A geobacterRustPackages.cargo || exit 1) | cachix push geobacter-rs
  rustfmt:
    needs: rustc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v9
        with:
          name: geobacter-rs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: mkdir -p ~/.config/nixpkgs/overlays && ln -s `pwd` ~/.config/nixpkgs/overlays/nixos-geobacter
      - run: (nix-build pkgs/default.nix --verbose --verbose --show-trace -A geobacterRustPackages.rustfmt || exit 1) | cachix push geobacter-rs
